version: '3.1'
services:
  schema-collector:
    image: schema_collector
    build: .
    env_file:
      - ./.env
    volumes:
      - ./schemaspy:/output
      - ./dump:/dump
      - ./diff:/diff
      - ./run.sh:/run_.sh
    container_name: "schema-collector"
    command: >
      sh -c '
      chmod +x run_.sh &&
      sh run_.sh
      '