version: '3.1'
services:
  schema-collector:
    image: schema_collector
    build: .
    env_file:
      - ./.env
    volumes:
      - ./output:/output
    container_name: "schema-collector"
    command: >
      sh -c '
      ls -la &&
      sh run_schemaspy &&
      sh upload_repository
      '