version: '3.1'
services:
  schema-collector:
    image: schema-collector
    build: .
    env_file:
      - ./.env
    volumes:
      - ./schemaspy:/output
      - ./dump:/dump
      - ./diff:/diff
    container_name: "schema-collector"
    command: sh run.sh